name: Build and Test C++ Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: docker://gcc:latest

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build the project
        run: make

      - name: Run the program
        run: Code_soal_1.cpp

