name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Code_soal_1
      run: ./Code_soal_1.cpp
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
